### PR TITLE
CameraLink Development Updates

### PR DESCRIPTION
**Pull request by ruck314**
### Description
- Updating all the "softReset" to "initialize" (starting from rogue v3.5.0)
- fixing Opal1000 naming typo
- bug fix for ClinkChannel resets

### CODE REVIEW

**Comment by bengineerd** [comment]
Why change the default status and error bits for Pgp3Axil?

**Comment by ruck314** [comment]
The `SyncStatusVector` can take a lot of resources if you have a large `WIDTH_G` and large `CNT_WIDTH_G`.  I was unable to fit 2 PGPv3 links into a Kintex-7 160T because of this.  Do you think that we need more than 8-bit for the default?  I think 12-bit or 16-bit would be more reasonable than 32-bits for defaults with respect to FPGA resources.

**Comment by bengineerd** [comment]
Lets do 16 bits for status and 8 for error counting

**Comment by ruck314** [comment]
@bengineerd: Done.  Applied this to caaf1b2

**Pull request merged**
