### PR TITLE
Rogue v2 support and Larry's changes

### PR DESCRIPTION
**Pull request by slacrherbst**

### CODE REVIEW

**Comment by bengineerd** [comment]
I think we should do the hack to make Command.toggle backward compatible to v2.
Also, I think we should delete RegisterVector and use SlvDelay instead since they are rather redundant.

**Comment by bengineerd** [comment]
Oh wait, we already did the hack in Command. It should work find in rogue v2 to pass Command.toggle as the command function.

**Comment by slacrherbst** [comment]
I fixed the Command.toggle references.

**Comment by slacrherbst** [comment]
We can adjust the RegisterVector as a second merge/commit.

**Pull request merged**
