### PR TITLE
Rogue Tcp features

### PR DESCRIPTION
**Pull request by bengineerd**
### Description

- Add `RoguePgp2bSim` to wrap Pgp2b around RogueTcpStream.
- Set TCP port range for Rogue sim modules.
- Make RogueSideBand bi-directional
- Update default sim version of GTP to 2.0
- Fix bug in RogueTcpStream.c where TUserFirst got dropped on single txn frames.

### CODE REVIEW

**Comment by slacrherbst** [comment]
I assume there is the equivalent changed to the side band protocol in rogue?

**Comment by bengineerd** [comment]
The rogue sideband protocol gets updated in this PR:
https://github.com/slaclab/rogue/pull/363

**Comment by ruck314** [comment]
@bengineerd Is this ready to merge?

**Comment by bengineerd** [comment]
Almost. Probably tomorrow.

**Comment by bengineerd** [comment]
I think I'm ready to merge this.

**Pull request merged**
