### PR TITLE
AxiVersion-update

### PR DESCRIPTION
**Pull request by ruck314**
changed GitHashShort from RW variable to RO, set FpgaReload, FpgaReloadHalt, and FpgaReloadAddress to hidden because these 3 variable not indended for GUI use

### CODE REVIEW

**Comment by ruck314** [comment]
>> I think FpgaReload is intended for GUI use
During this period because GUI tends to have polling turned on, I get lots of time out messages when I execute the FpgaReload (maybe acceptable during this period)

**Comment by bengineerd** [comment]
I think that's acceptable to have timeouts during FPGA reload.

If you want to avoid those, you can link the FPGA Device 'enable' to a 'LinkActive' variable on the system side. I usually use Pgp2bAxi.RemLinkReady. (I'm not sure we've merged this feature yet, but we will soon). This probably also works for RSSI links, but probably not for pure UDP links, since you have no way to tell the link state.

**Comment by bengineerd** [comment]
I made FpgaReload visible again. Are we ok with this?

**Comment by ruck314** [comment]
I guess so

**Pull request merged**
