### PR TITLE
Use the ../ruckus/releaseNotes.py instead

### PR DESCRIPTION
**Pull request by ruck314**
### Description
- Too many copies of releaseNotes.py
  - Difficult to maintain changes across all of them
- Migrating repos to use the common `../ruckus/releaseNotes.py instead`

### CODE REVIEW

**Comment by bengineerd** [comment]
Does this script need to run from Travis?

**Comment by slacrherbst** [comment]
Before you do that. Please look at the latest Rogue releaseNotes. it is meant to run from travis
Maybe give me a bit to add a few more features to it and then I will put it in Ruckus, and do a test run for using the Ruckus version across repos.

**Comment by slacrherbst** [comment]
Basically we need two scripts. One script to release a non build output repo, suck as Ruckus, Rogue, surf, amc-carrier core etc. This script gets run from travis when a tag is created and generates the release with appropriate release notes attached.

The second is a script run from the command line to generate a release for a repo that has a firmware build output as part of it.

**Comment by ruck314** [comment]
@slacrherbst: I think it's releated to this JIRA ticket .....
https://jira.slac.stanford.edu/browse/ESCORE-551

**Comment by slacrherbst** [comment]
This PR is deprecated by #645

**Comment by ruck314** [comment]
deprecated by PR#645

**Pull request closed without merging**
