### PR TITLE
stream tap

### PR DESCRIPTION
**Pull request by slacrherbst**

### CODE REVIEW

**Comment by ruck314** [comment]
I would expose the PIPELINE_G of AxiStreamMux & AxiStreamDeMux to the top-level.

**Comment by slacrherbst** [comment]
As separate generics or a common one?

**Comment by ruck314** [comment]
90% use case is common if needed.

**Comment by ruck314** [comment]
Maybe at a later time we should consider restricting the range of all these pipeline generics to "Range 0 to 1".  2 or more doesn't really help with timing and only increases latency and resources

**Pull request merged**
