### PR TITLE
Expose RX Equalizer choice in Gtx7Core to users of Pgp2bGtx7FixedLat, Pgp2bGtx7MultiLane, and Pgp2bGtx7VarLat.

### PR DESCRIPTION
**Pull request by jgthayer**
Expose RX Equalizer choice in Gtx7Core to users of Pgp2bGtx7FixedLat, Pgp2bGtx7MultiLane, and Pgp2bGtx7VarLat.

### Description
Gtx7Core provides the ability to select LPM or DFE as the RX Equalizer in the GTX, the 3 PGP2 blocks that use Gtx7Core hardcode this to DFE. COB versions 10 and 11, require LPM to function. These changes just expose the Gtx7Core generic (RX_EQUALIZER_G) to the outside world.

### CODE REVIEW

**Comment by ruck314** [comment]
@jgthayer Are you ready to merge?

**Comment by jgthayer** [comment]
Ready when you all are. Go for it.

**Comment by jgthayer** [comment]
What's the best way to be notified when this gets merged into master or otherwise released?

**Comment by ruck314** [comment]
image
You can click on "watch" and select one of the option.  Then you will get emails with respect to the watch option that you have selected.

**Comment by jgthayer** [comment]
Great thanks!

**Pull request merged**
