### PR TITLE
ESCORE-306 - Adding interleave support to RSSI

### PR DESCRIPTION
**Pull request by ruck314**
Change summary
 - Add VERSION field to Packetizer2 header
 - Add field constants for Packetizer2 header and tail
 - RSSI now uses Packetizer2 when interleaving is enabled
 - Add field constants for PGP3
 - PGP3 internals made compatible with Packetizer2 VERSION field changes.

### CODE REVIEW

**Comment by ruck314** [comment]
@slacrherbst: https://github.com/slaclab/dev-board-examples/tree/ESROGUE-153

**Comment by bengineerd** [comment]
I don't think we need to revert back to PacketizerV1 when the interleave disable generic is set. Packetizer2 works in both cases. Everything really happens in the AxiStreamMux that feeds it.

**Comment by ruck314** [comment]
```I don't think we need to revert back to PacketizerV1```

We have deployed systems with RSSI+PacketizerV1.  We need to be backwards compatible for with these systems.

**Comment by bengineerd** [comment]
I guess the Packetizer protocol is sort of baked into the RSSI protocol.
Do you think it's worth having an option for disabled interleave with Packetizer2?

**Comment by ruck314** [comment]
@bengineerd/@slacrherbst: Are we ready to merge?

**Comment by bengineerd** [comment]
We're going to put the version field in.
I'm working on that now.
I'll also have to update PGP3 once I do that.

**Pull request merged**
