### PR TITLE
Fixed AxiStreamPacketizer2 CRC Bug

### PR DESCRIPTION
**Pull request by ruck314**
### Description
- fixed AxiStreamPacketizer2 CRC bug

### Note
This bug got exposed after this previous bug fix:
https://github.com/slaclab/surf/commit/78d17fb031c949088796b858742531db524fabad#diff-1ddf0c59e774cc5f8b1a50f39af03109

### JIRA
[ESCORE-368](https://jira.slac.stanford.edu/browse/ESCORE-368)

### CODE REVIEW

**Comment by ruck314** [comment]
```

**Comment by ruck314** [comment]
```

**Comment by ruck314** [comment]
```
rogue.protocols.packetizer.CoreV2(True,True) # ibCRC = True, obCRC = True
```
Confirmed that the SW-to-FW w/ (ibCRC = True) now works with this FW fix.  Working on the FW-to-FW test build now.

**Comment by till-s** [comment]
Could you please explain what impact this bug has on software - is the SW->FW CRC affected and if so, how?; is the FW->SW CRC affected and if so, how?

How does the fix affect software - are any changes to software required (SW->FW CRC and/or FW->SW CRC) ?

Thanks

**Comment by ruck314** [comment]
This bug fix does not affect software unless the software was checking CRC on the inbound packets.

**Comment by bengineerd** [comment]
Would this affect PGP3? PGP3 uses PacketizerV2 to generate it's CRCs.

**Pull request merged**
