### PR TITLE
Depreciating surf.misc.GenericMemory.py

### PR DESCRIPTION
**Pull request by ruck314**
### Description
- Depreciating surf.misc.GenericMemory.py

### JIRA
[ESROGUE-288](https://jira.slac.stanford.edu/browse/ESROGUE-288)

### CODE REVIEW

**Comment by ruck314** [comment]
@bengineerd: Any comments on this PR?

**Comment by bengineerd** [comment]
I think the `readBlocks`, `writeBlocks` and `checkBlocks` overloads should probably just be deleted. I had added these to basically force checkEach when debugging. I think it turned out to be an SRP bug or something like that, and there's no need to checkEach anymore.

**Comment by ruck314** [comment]
@bengineerd: Any other modifications that you want to do before you approve?

**Comment by bengineerd** [comment]
Someone who uses it should verify that it still works.

**Comment by ruck314** [comment]
https://github.com/slaclab/rogue/wiki/MemoryDevice-example
Deleted _GenericMemory.py because we will use pyrogue.MemoryDevice for atlas-rd53

**Pull request merged**
