### PR TITLE
Convert simulation receivers to non blocking instead of timeout

### PR DESCRIPTION
**Pull request by slacrherbst**
The previous versions were not doing non-blocking receive calls to the zeromq sockets. Instead they were waiting for a period of time. This was causing simulations to run slow.

### CODE REVIEW

**Comment by ruck314** [comment]
@slacrherbst I got this error message:

**Comment by slacrherbst** [comment]
ZMQ Seems to be missing. which setup did you source?

**Comment by ruck314** [comment]
```
source /afs/slac.stanford.edu/g/reseng/zeromq/4.3.1/settings.csh
```

**Comment by slacrherbst** [comment]
Use this one:

source /afs/slac.stanford.edu/g/reseng/zeromq/4.2.1/settings.csh

I need to fix the simulation makefile to better figure out the zmq paths. The 4.3.1 install uses cmake and the library find routine is not working properly.

**Comment by ruck314** [comment]
image
Running 256 TDEST on a single DMA lane and running a LOT faster now.  Everything seems to be working as it should.

**Comment by ruck314** [comment]
@slacrherbst: Ready to merge?

**Pull request merged**
