### PR TITLE
Reorganizing the AXI source code 

### PR DESCRIPTION
**Pull request by ruck314**
### Description
1)  moved packetizer source code from axi/rtl to protocols/packetizer 
2)  moved dma source code from axi/rtl to axi/dma 
2)  moved bridge source code from axi/rtl to axi/bridge 
3)  moved AXI-Lite source code from axi/rtl to axi/axi-lite 
4)  moved AXI-stream source code from axi/rtl to axi/axi-stream
5)  moved AXI4/AXI3 source code from axi/rtl to axi/axi-mem

### CODE REVIEW

**Comment by ruck314** [comment]
Note: "axi/axi-mem" seemed like a better choice than "axi/axi".  I am open to a better name if you can think of one (like "axi/axi-core" or "axi/base").

**Comment by bengineerd** [comment]
maybe axi/axi4 (or axi-4)?

**Comment by ruck314** [comment]
Updated to axi/axi4

**Comment by bengineerd** [comment]
Perhaps there should be `rtl` and `tb` folders in each of `axi-lite`, `axi-stream`, `axi4`, etc.

What does everyone else think?

**Pull request merged**
