### PR TITLE
Merge pgp3-dev into master

### PR DESCRIPTION
**Pull request by bengineerd**
Somehow the original PR got merged prematurely by accident. I've recreated it.

This is a huge merge. Everyone please look closely at the diffs and make sure you're ready for all of this to go into the master branch.

### CODE REVIEW

**Comment by ruck314** [comment]
The changes in this pull request include pull request#121.  Does the modifications in 'getAxiLen-dev' branch make sense?
https://github.com/slaclab/surf/pull/121

**Comment by ruck314** [comment]
@bengineerd: Added GTX7 support for standard 10.3125Gbps and support for 6.25Gbps (for 7-series that only support GTs up to 6.6Gbps)

**Comment by slacrherbst** [comment]
Can we merge?

**Comment by bengineerd** [comment]
Ok, here we go.

**Pull request merged**
